/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#dadcde",
        "on-secondary": "#ffffff",
        "on-surface": "#0b1c30",
        "secondary-fixed-dim": "#bec6e0",
        "inverse-surface": "#213145",
        "on-primary-container": "#dad7ff",
        "surface-bright": "#f8f9ff",
        "on-surface-variant": "#464555",
        "tertiary": "#46494b",
        "secondary-fixed": "#dae2fd",
        "surface-container-low": "#eff4ff",
        "tertiary-container": "#5e6163",
        "tertiary-fixed": "#e0e3e5",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-error-container": "#93000a",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed-dim": "#c4c7c9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "primary-container": "#4f46e5",
        "surface-container": "#e5eeff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "on-primary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "secondary": "#565e74",
        "surface-tint": "#4d44e3",
        "surface": "#f8f9ff",
        "on-tertiary-fixed": "#191c1e",
        "secondary-container": "#dae2fd",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed-variant": "#3f465c",
        "background": "#f8f9ff",
        "primary": "#3525cd",
        "outline": "#777587",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed": "#131b2e",
        "primary-fixed": "#e2dfff",
        "on-primary-fixed": "#0f0069",
        "on-background": "#0b1c30",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed-variant": "#444749",
        "inverse-primary": "#c3c0ff",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
